// <auto-generated />
using Covid_World.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Covid_World.Migrations
{

//    [DbContext(typeof(Covid19wDbContext))]
//    [Migration("20200620090751_Covid19W")]
//    partial class Covid19W
//    {
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "3.1.5")
//                .HasAnnotation("Relational:MaxIdentifierLength", 64);

//            modelBuilder.Entity("Covid_World.DBContext.Coviddatas", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnName("ID")
//                        .HasColumnType("int(11)");

//                    b.Property<string>("CaseActive")
//                        .HasColumnName("Case_Active")
//                        .HasColumnType("varchar(45)")
//                        .HasMaxLength(45)
//                        .IsUnicode(false);

//                    b.Property<string>("CaseCritical")
//                        .HasColumnName("Case_Critical")
//                        .HasColumnType("varchar(45)")
//                        .HasMaxLength(45)
//                        .IsUnicode(false);

//                    b.Property<string>("CaseNew")
//                        .HasColumnName("Case_new")
//                        .HasColumnType("varchar(45)")
//                        .HasMaxLength(45)
//                        .IsUnicode(false);

//                    b.Property<string>("CaseRecovered")
//                        .HasColumnName("Case_Recovered")
//                        .HasColumnType("varchar(45)")
//                        .HasMaxLength(45)
//                        .IsUnicode(false);

//                    b.Property<string>("CaseTotal")
//                        .HasColumnName("Case_Total")
//                        .HasColumnType("varchar(45)")
//                        .HasMaxLength(45)
//                        .IsUnicode(false);

//                    b.Property<string>("Country")
//                        .IsRequired()
//                        .HasColumnType("varchar(45)")
//                        .HasMaxLength(45)
//                        .IsUnicode(false);

//                    b.Property<string>("DeathNew")
//                        .HasColumnName("Death_new")
//                        .HasColumnType("varchar(45)")
//                        .HasMaxLength(45)
//                        .IsUnicode(false);

//                    b.Property<string>("DeathTotal")
//                        .HasColumnName("Death_Total")
//                        .HasColumnType("varchar(45)")
//                        .HasMaxLength(45)
//                        .IsUnicode(false);

//                    b.Property<string>("Time")
//                        .IsRequired()
//                        .HasColumnType("varchar(45)")
//                        .HasMaxLength(45)
//                        .IsUnicode(false);

//                    b.HasKey("Id");

//                    b.ToTable("coviddatas");
//                });

//            modelBuilder.Entity("Covid_World.DBContext.User", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int(11)");

//                    b.Property<string>("Cognome")
//                        .HasColumnType("varchar(45)")
//                        .HasMaxLength(45)
//                        .IsUnicode(false);

//                    b.Property<string>("Email")
//                        .IsRequired()
//                        .HasColumnType("varchar(45)")
//                        .HasMaxLength(45)
//                        .IsUnicode(false);

//                    b.Property<string>("Nome")
//                        .HasColumnType("varchar(45)")
//                        .HasMaxLength(45)
//                        .IsUnicode(false);

//                    b.HasKey("Id");

//                    b.ToTable("user");
//                });
//#pragma warning restore 612, 618
//        }
//    }

}
